### ISSUE TITLE
Functions may not be defined within control directives

### ISSUE THREAD

**Issue by dirkpeter** [phlppschrr/gulp-compass-imagehelper#6]
when working with a current spec of libsass, i run into an error compiling the css, after using gulp-compass-imagehelper to create the `_image-map.scss` partial:

> Error in plugin 'sass'
> Message:
>     src/sass/variables/_image-map.scss
> Error: Functions may not be defined within control directives or other mixins.
>         on line 12 of src/sass/variables/_image-map.scss
>        @function compassImagehelper_getList($image) {
>    --^

related issue: Incorrectly allowing functions to be defined in control directives or mixins
» https://github.com/sass/libsass/issues/1550

note: i know i can add a custom template and adjust the partial-output, just wanted to inform about the issue

**Comment by npostulart** [comment]
I noticed the same and fixed it in the forked library gulp-sass-image
https://github.com/npostulart/gulp-sass-image/commit/b92ba7b86cd8fa73560b40d10b44d79908cf6852

**Comment by phlppschrr** [comment]
Thank you both! Publishing this now to npm..
